server:
  port: 8881
rpc:
  client:
    load-balance: random
    serialization: PROTOSTUFF
    transport: netty
    registry: zookeeper
    registry-addr: 172.26.134.157:2181
    timeout: 5000

logging:
  level:
    com.xk.rpc: info