server:
  port: 8881
rpc:
  client:
    transmission: netty
    serialization: JSON
    load-balance: random
    register: zookeeper
    register-addr: 127.0.0.1:2181
    timeout: 5000
    retry-strategy: randomRetryStrategy
    enable-ssl: false
logging:
  level:
    com.xk.rpc: info